# Generated by Django 4.1.5 on 2023-01-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='start_price',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='auction',
            name='url',
            field=models.CharField(default='Unknown', max_length=512),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
