# Generated by Django 4.1.5 on 2023-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_start_price_auction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateField(),
        ),
    ]
