# Generated by Django 4.1.5 on 2023-01-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='date',
        ),
    ]
