# Generated by Django 4.1.5 on 2023-01-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_delete_watchlist_auction_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('item', models.CharField(max_length=64)),
                ('watchlist', models.BooleanField(default=False)),
            ],
        ),
    ]
