# Generated by Django 4.1.5 on 2023-01-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
