# Generated by Django 4.1.5 on 2023-01-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comment_item_comment_message_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='comment',
        ),
    ]
