# Generated by Django 4.1.5 on 2023-01-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_message_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='Empty', upload_to='img'),
        ),
    ]
